MyTutor/MyTutor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^Tutorial/', include('Tutorial.urls')),
    url(r'^accounts/login', RedirectView.as_view(url='/Tutorial/login')),
    url(r'^password_reset/$', auth_views.password_reset, {
        'post_reset_redirect': 'done/'
    }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

	#rl(r'^Tutorial/login/$', auth_views.login, name='login'),
    #url(r'^Tutorial/logout/$', auth_views.logout, {'next_page': '/Tutorial/searchTutor/'}, name='logout'),
    #url(r'^Tutorial/searchTutors/', include('Tutorial.urls')),  #when someone clicks search tutor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyTutor/Tutorial/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm,password_reset_complete
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout
app_name = 'Tutorial'
urlpatterns = [
    url(r'^$', views.login, name='home'),
    url(r'^admin/$', views.adminpage, name='adminpage'),
    url(r'^mytutor/$', views.mytutor, name='mytutor'),
    url(r'^mytutor/withdraw$', views.tutorwithdraw, name='tutorwithdraw'),
    url(r'^admin/triggersession$', views.triggersession, name='triggersession'),
    url(r'^(?P<myuser_id>[0-9]+)/$', views.index, name='index'),
    url(r'^(?P<myuser_id>[0-9]+)/searchTutors/(?P<tutor_id>[0-9]+)/$', views.tutorpage, name='tutorpage'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/$', views.myaccount, name='myaccount'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mybooking/$', views.mybooking, name='mybooking'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mybooking/evaluate/(?P<tutorial_sessions_id>[0-9]+)/$', views.evaluate,
        name='evaluate'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/myprofile/$', views.myprofile, name='myprofile'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mywallet/$', views.mywallet, name='mywallet'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mytransaction/$', views.mytransaction, name='mytransaction'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mywallet/deposit/$', views.deposit, name='deposit'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mywallet/withdraw/$', views.withdraw, name='withdraw'),
    url(r'^(?P<myuser_id>[0-9]+)/message/$', views.message, name='message'),
    url(r'^(?P<myuser_id>[0-9]+)/timeslot/(?P<tutor_id>[0-9]+)/$', views.selectbooking, name='timeslot'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mybooking/cancelled/(?P<tutorial_sessions_id>[0-9]+)/$', views.cancelbooking, name='cancelbooking'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register_page, name='register'),
    url(r'^(?P<myuser_id>[0-9]+)/searchTutorName/$', views.search_tutor_name, name='search_tutor_name'),
    url(r'^(?P<myuser_id>[0-9]+)/searchTutorTag/$', views.search_tutor_tag, name='search_tutor_tag'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/tutorTimeslot/(?P<tutor_id>[0-9]+)/$', views.tutorTimeslot, name='tutorTimeslot'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/tutorTimeslotSelect/(?P<tutor_id>[0-9]+)/$', views.tutorTimeslotSelecting, name='tutorTimeslotSelecting'),

    #url(r'^registerSuccess/$', views.register_page, name='registerSuccess'),
    #test
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyTutor/Tutorial/views.py
from ast import literal_eval
from django.contrib import auth
from django.template import RequestContext
from django.shortcuts import redirect
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date, datetime, time, timedelta
from Tutorial.forms import *
import time
from Tutorial.models import *
from django.template import RequestContext
import logging
import re
# Get an instance of a logger
logger = logging.getLogger(__name__)
from django.contrib.auth import views as auth_views

from django.conf import settings
import smtplib
from django.core.mail import send_mail
import operator
import logging
from decimal import Decimal

# Get an instance of a logger
logger = logging.getLogger(__name__)

from .forms import SearchForm


COMMISION = 1.05
# Create your views here.
class HomePageView(TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'index.html', context=None)

class SearchedTutor(object):
    tutor = ""
    hourly_rate = 0
    tags = []
    teachCourse = []
    def __init__(self, tutor, hourly_rate, tags, teachCourse):
        self.tutor = tutor
        self.hourly_rate = hourly_rate
        self.tags = tags
        self.teachCourse = teachCourse

#####homepage###
def home(request):
    if not request.user.is_authenticated() or request.user.is_anonymous():
        #every function will have this, to make sure guest cannot visit personal account by manipulating url
        return render(request, 'home.html')
    if not MyUser.objects.filter(user=request.user):
        return HttpResponseRedirect('/Tutorial/admin/')
    myuser = MyUser.objects.get(user=request.user) #fixme if an admin want to go to Tutorial/, he is not a myuser
    return HttpResponseRedirect('/Tutorial/' + str(myuser.id)) #searchTutors/'+str(request.user.id)
####login####
def login(request):
    if request.user.is_authenticated(): #visitor or client
        if not MyUser.objects.filter(user=request.user):
            return HttpResponseRedirect('/Tutorial/admin/') # Assume all tutors share a same page, so noneed for user.id+ str(user.id))
        myuser = MyUser.objects.get(user=request.user)
        return HttpResponseRedirect('/Tutorial/' + str(myuser.id)) #searchTutors/'+str(request.user.id)

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = auth.authenticate(username=username, password=password) #if sucess, should get not none

    if user is not None and user.is_active:
        auth.login(request, user)
        if not MyUser.objects.filter(user=request.user):
            return HttpResponseRedirect('/Tutorial/admin/') # Assume all tutors share a same page, so noneed for user.id+ str(user.id))
        myuser = MyUser.objects.get(user=request.user)
        return HttpResponseRedirect('/Tutorial/' + str(myuser.id))
    else:
        return render(request, 'registration/login.html')

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/Tutorial/')
"""def password_reset(request):
    return render( 'registration/password_reset_form.html')

def password_reset_done(request):
    return render('/registration/password_reset_done.html')

def password_reset_confirm(requst):
    return HttpResponseRedirect('/Tutorial/')

def password_reset_complete(request):
    return HttpResponseRedirect('/Tutorial/')"""


####search tutor####
def index(request, myuser_id):
    show_tags = []
    if not request.user.is_authenticated() or request.user.is_anonymous(): #visitor or client
        return render(request, 'home.html')
    if not MyUser.objects.filter(user=request.user):
        return HttpResponseRedirect('/Tutorial/admin/')
    myuser = MyUser.objects.get(user=request.user)  # myuser = get_object_or_404(MyUser, pk=myuser_id)
    #fixme I do this to make sure you are the person you should be, you cannot be someone else
    #fixme  but I haven't tried how to also relink the url i.e. if id = 2 enter 3/..., the content can be
    #fixme 2's now ,but the url shows 3 still

    all_tutors = Tutor.objects.filter(showProfile=True)
    for tut in all_tutors:
        show_tags.append(tut.tag_set.all())
    private_tutors = PrivateTutor.objects.all()
    courses= Course.objects.all()
    zipped = zip(all_tutors, show_tags)
    params = {"user": myuser, "latest_Tutor_list": all_tutors, "tutors": zipped, 'courses': courses}
    return render(request, 'searchtutors/index.html', params)

def adminpage(request):
    return render(request, 'admin.html')

def triggersession(request):
    time = request.POST['time']
    timeformat = '%Y%m%d%H%M'
    try:
        bookingtime = datetime.strptime(time, timeformat)
    except Exception as e:
        return render(request, 'admin.html', {"msg": "Please enter format: YYYYmmddHHMM"})
    logger.error("trigger time wanted at" + time)
    if bookingtime.minute != 0 and bookingtime.minute != 30:
        return render(request, 'admin.html', {"msg": "Minutes is not 00 or 30, so no effect"})
    locksession(time)

    endsession(time)
    return render(request, 'admin.html', {"msg": "Setting success"})

def locksession(mytime):
    timeformat = '%Y%m%d%H%M'
    reftime = datetime.strptime(mytime, timeformat)
    if reftime.weekday() == 6 and reftime.hour == 0 and reftime.minute == 0:
        ## update the week of timeslot, if it is Sunday 00:00, then the timeslot should switch to a new week
        for tutor in Tutor.objects.all():
            if tutor.hourly_rate == 0:
                trigger = 2
            else: trigger = 1 #this is to distinguish between the two kinds
            slotlist = tutor.timeslot
            mid = 168 * trigger
            first_half = slotlist[mid: ] #the first half should be the second half of previous slot, next week has become the current week
            second_half = '1' * mid
            tutor.timeslot = first_half + second_half
            tutor.save()

    for slot in TutorialSession.objects.all(): #for this tutor's session, for student is this student , for loop
        ## begin tutorial
        if slot.starttime == mytime:
            if slot.status == 0 or slot.status == 1: #meaning that this session is upcoming but not canceled
                slot.status = 5 #set to in progress
                slot.save()
        else:
        ## lock cancel
            nowbooking = datetime.strptime(slot.starttime,timeformat)  # this is the yy mm dd format for what student wants to book
            bookingtime = time.mktime(nowbooking.timetuple())  # transfrom nowbooking into time format, should expect this to be later
            bookingreftime = time.mktime(reftime.timetuple()) # transform the reftime into time format
            logger.error("This is slot's time " + str(bookingtime) + " and this is now time " + str(bookingreftime) + " and this is the time delta " + str((bookingtime - bookingreftime) / 3600))
            if (slot.status == 0 and (bookingtime - bookingreftime) / 3600 <= 24): #if it is upcoming, make it cannot be canceled
                slot.status = 1
                slot.save()

    ## close booking

    now = reftime #only test for within one week!!
    #now = datetime.now()
    showingtime = time.mktime(datetime(now.year, now.month, now.day, 0, 0).timetuple())
    bookingtime = time.mktime(now.timetuple()) #transfrom nowbooking into time format
    #later on with beginAllSessions, we update the available string for every tutor each week at the end
    #day difference is because the 14-day long string starts from this Sunday, the first day of the week
    hour_diff = (bookingtime - showingtime) / 3600
    weekday = (1 + now.weekday()) % 7  # Monday is 0 ... Sunday is 6, but Sunday is the first day of the week, transform to 0
    if reftime.minute == 0:
        for tutor in Tutor.objects.all():

            if tutor.hourly_rate == 0:
                diff = 2
            else: diff = 1

            # modify timeslot string
            timeslot = list(tutor.timeslot)
            logger.error("This is the index" + tutor.myuser.user.username + " " + str(len(timeslot)) + " " + str(weekday * 24 * diff + int (hour_diff * diff) + 24 * diff) + " and " + str(weekday * 48 + hour_diff * 2 + 48))
            logger.error("Finally " + str(weekday * 24 * diff + int (hour_diff * diff) + 24 * diff))
            timeslot[weekday * 24 * diff + int (hour_diff * diff) + 24 * diff] = '3' #meaning this session has passed the state to be modified

            #weekday * 24 * diff is how many 24 hours has passed
            #int (hour_diff * diff) means starting from today to 'now', hong long has passed
            #24 * diff means 24 hours passed
            #this function works when we are in the first week in timeslot string, because it should be updated every Saturday night, why now
            #I pretend today is next Wednesday and it fails is because it change the time of the current week, but in practical the next week
            #should be the reall current week, so it works well
            tutor.timeslot = "".join(timeslot)
            tutor.save()
    else: #then only contracted tutor needed in this case, but currently now working because no interface for half an hour yet
        half_hour_diff = int((bookingtime - showingtime) / 1800)
        weekday = (1 + now.weekday()) % 7  # Monday is 0 ... Sunday is 6, but Sunday is the first day of the week, transform to 0
        for tutor in Tutor.objects.filter(hourly_rate=0):

            # modify timeslot string
            timeslot = list(tutor.timeslot) 
            timeslot[weekday * 48 + half_hour_diff + 48] = '3' #meaning I book the session, 0 only means tutor doesn't want this session to be booked
            logger.error(

MyTutor/Tutorial/templates/Menu.html
<!DOCTYPE html>
<html style="height : 100%;">
	<head>
		<title>Main page</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
         <link rel="stylesheet" href="/static/bootstrap/css/style.css">
        <link rel="stylesheet" href="/static/bootstrap/css/style1.css">
         <link rel="stylesheet" href="/static/bootstrap/css/responsive.css">

        <script type="text/javascript" src="/static/bootstrap/js/jquery.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/tether.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery-ui.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/moment.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery.smartmenus.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery.parallax.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery.shuffle.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/owl.carousel.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/map.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/main.js"></script>
            <script>{% block script %}{% endblock %}</script>
            <script>{% block script1 %}{% endblock %}</script>
	</head>

	<body style="height : 100%;">
		<header class="header">
      <div class="header-bottom">
        <nav class="navbar navbar-universal navbar-custom">
          <div class="container">
            <div class="row">
              <div class="col-lg-3">
                <div class="logo"><a href="index.html" class="navbar-brand page-scroll"><img src="/static/bootstrap/images/logo/logo.png" alt="logo"></a></div>
              </div>
              <div class="col-lg-9">
                <div class="navbar-header">
                  <button type="button" data-toggle="collapse" data-target=".navbar-main-collapse" class="navbar-toggle"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                </div>
                <div class="collapse navbar-collapse navbar-main-collapse">
                  <ul class="nav navbar-nav navbar-right">

                      {% if request.user.is_authenticated %}
                    <li><a href="#">Home</a></li>
                    <li><a href="{% url 'Tutorial:index' user.id %}">Search Tutors</a></li>
                    <li><a href="{% url 'Tutorial:mybooking' user.id %}">My Account</a></li>
                    <li><a href="{% url 'Tutorial:message' user.id %}">Messages</a></li>
                    <li><a href="{% url 'Tutorial:logout' %}">Logout</a></li>
                      {% else %}<li><a href="#">Home</a></li>
                    <li><a href="{% url 'Tutorial:login' %}">Search Tutors</a></li>
                    <li><a href="{% url 'Tutorial:login' %}">My Account</a></li>
                    <li><a href="{% url 'Tutorial:login' %}">Messages</a></li>
                    <li><a href="{% url 'Tutorial:login' %}">Login</a></li>
                      {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </nav>
      </div>
</header>
        <div style="height : 100%">
        {% block content %}{% endblock %}
        </div>
	</body>
</html>

MyTutor/Tutorial/templates/admin.html
<!DOCTYPE html>
<html>
<head>
	<title>Cron Job Page</title>
</head>
<body>
	<form method='POST' action="{% url 'Tutorial:triggersession' %}">
		Time: <input type='text' name='time' size='30'>
		<input type='submit' value='submit'>
	</form>
    <p>{{msg}}</p>
</body>
</html>

MyTutor/Tutorial/templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}" />
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}" />{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

MyTutor/Tutorial/templates/home.html
{% extends "registration/login.html" %}

MyTutor/Tutorial/templates/index.html
<!-- howdy/templates/index.html -->
<!DOCTYPE html>
<html style="height : 100%;">
	<head>
		<title>Main page</title>
		<meta name="viewport" content="width=device-width,maximum-scale=2">
	</head>

	<body style="height : 100%;">
		<div id="header" class="header" style=" background-color: #191970;  margin : auto; font-size : 14pt; padding: 10px; text-align : center; font-family : Futura, Arial;">
			<table style="width : 100%;">
				<tr>
					<th><a id="Home" href="" style="color : white; text-decoration:none;">Home</a></th>
					<th><a id="SearchTutors" href="{% url 'Tutorial:index'%}" style="color : white; text-decoration:none;">Search Tutors</a></th>
					<th><a id="MyAccount" href="{% url 'Tutorial:myaccount' 5 %}" style="color : white; text-decoration:none;">My Account</a></th>
					<th><a id="Messages" href="" style="color : white; text-decoration:none;">Messages</a></th>
					<th><a id="Mode" href="" style="color : white; text-decoration:none;">Student Mode</a></th>
				</tr>
			</table>
		{% block content %}{% endblock %}
        </div>
		<h3 style="background-color: #B0C4DE; color : #2F4F4F;  padding : 5px; text-align : center; border : 0px solid #708090; margin : 0;">Latest tutor information</h3>
		<div id="TutoInfo" style="background-color : #F8F8FF; padding : 7px; height : 60%;">
			<img src="logo.jpg" style="width : 20%; ">
			<ul style="float : right;  text-align : left; color : #778899;">

				{%for Tutor in latest_Tutor_list%}
				<div>
					<p><a href="{% url 'Tutorial:tutorpage' Tutor.id %}">{{Tutor.id}}   {{Tutor.user.name}}</a></p>

					<!--<p>{{Tutor.hourly_rate}}</p>-->
				</div>
				{%endfor%}
			</ul>
		</div>
	</body>
</html>

MyTutor/Tutorial/templates/mytutor.html
<!DOCTYPE html>
<html style="height : 100%;">
    Wallet: {{user.wallet.balance}}
	<head>
		<title>MyTutor Transaction</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
         <link rel="stylesheet" href="/static/bootstrap/css/style.css">
        <link rel="stylesheet" href="/static/bootstrap/css/style1.css">
         <link rel="stylesheet" href="/static/bootstrap/css/responsive.css">

        <script type="text/javascript" src="/static/bootstrap/js/jquery.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/tether.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery-ui.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/moment.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery.smartmenus.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery.parallax.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/jquery.shuffle.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/owl.carousel.min.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/map.js"></script>
  <script type="text/javascript" src="/static/bootstrap/js/main.js"></script>
    </head>
<body>
    <section class="section">
	</form>
      <div class="container">
        <div class="title-main"><h2 class="h2">Transaction records</h2></div>

        <div class="row">
          <div class="col-lg-3 col-md-4 col-sm-6">
            <h3 class="service_title"><i class="fa fa-calendar"></i> Transaction Time</h3>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6">
            <h3 class="service_title"><i class="fa fa-money"></i> Cashflow</h3>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6">
            <h3 class="service_title"><i class="fa fa-user-circle"></i> Tutor</h3>
          </div>
            <div class="col-lg-2 col-md-4 col-sm-6">
            <h3 class="service_title"><i class="fa fa-bar-chart"></i> Student</h3>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6">
            <h3 class="service_title"><i class="fa fa-bar-chart"></i> Information</h3>
          </div>
        </div>
          {% for session in  list %}
               <div class="row">
          <div class="col-lg-3 col-md-4 col-sm-6">
            <h3 class="service_title">{{ session.time }}</h3>
          </div>
          <div class="col-lg-2 col-md-4 col-sm-6">
            <h3 class="service_title"> ${{ session.cashflow }}</h3>
          </div>
                    <script>
                      if("{{ session.type }}" == '1'){
                          document.write(" <div class=\"col-lg-2 col-md-4 col-sm-6\">" +
                           "            <h3 class=\"service_title\">N/A</h3>" +
                           "          </div>" + " <div class=\"col-lg-2 col-md-4 col-sm-6\">" +
                           "            <h3 class=\"service_title\">N/A</h3>" +
                           "          </div>" + " <div class=\"col-lg-2 col-md-4 col-sm-6\">" +
                           "            <h3 class=\"service_title\">Withdraw</h3>" +
                           "          </div>");
                      }else if("{{ session.type }}" == '4'){
                          document.write( " <div class=\"col-lg-2 col-md-4 col-sm-6\">" +
                           "            <h3 class=\"service_title\">{{session.information.tutor.myuser.user.username}}</h3>" +
                           "          </div>" + " <div class=\"col-lg-2 col-md-4 col-sm-6\">" +
                           "            <h3 class=\"service_title\">{{session.information.student.myuser.user.username}}</h3>" +
                           "          </div>" + " <div class=\"col-lg-2 col-md-4 col-sm-6\">" +
                           "            <h3 class=\"service_title\">tutorial start from {{session.information.starttime}}</h3>" +
                           "          </div>");
                      }
                    </script>

        </div>
          {% endfor %}
      </div>
    </section>

     <div class="infoPanel">
	<form method='POST' action="{% url 'Tutorial:tutorwithdraw' %}">

         <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                  {% csrf_token %}
                  <label >Withdraw</label>
                  <input type="text" class="form-control" placeholder="Enter the number you want to withdraw." name="withdraw" size="30">
              </div>
            </div>
      </div>
        <div >
		<input type='submit' class ="btn btn-default" value='submit'>
        </div>
         {{msg}}
	</form>
    </div>
</body>
</html>

MyTutor/Tutorial/templates/search.html
{% extends "base.html" %}
{% block title %}Search Tutors{% endblock %}
{% block head %}Search Tutors{% endblock %}
{% block content %}
<form id="search-form" method="get" action=".">
 {{ form.as_p }}
 <input type="submit" value="search" />
</form>
<div id="search-results">
 {% if show_results %}
 {% include 'bookmark_list.html' %}
 {% endif %}
</div>
{% endblock %}