MyTutor/MyTutor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^Tutorial/', include('Tutorial.urls')),
    url(r'^accounts/login', RedirectView.as_view(url='/Tutorial/login')),
    url(r'^password_reset/$', auth_views.password_reset, {
        'post_reset_redirect': 'done/'
    }, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

	#rl(r'^Tutorial/login/$', auth_views.login, name='login'),
    #url(r'^Tutorial/logout/$', auth_views.logout, {'next_page': '/Tutorial/searchTutor/'}, name='logout'),
    #url(r'^Tutorial/searchTutors/', include('Tutorial.urls')),  #when someone clicks search tutor
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyTutor/Tutorial/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm,password_reset_complete
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import login, logout
app_name = 'Tutorial'
urlpatterns = [
    url(r'^$', views.login, name='home'),
    url(r'^admin/$', views.adminpage, name='adminpage'),
    url(r'^mytutor/$', views.mytutor, name='mytutor'),
    url(r'^mytutor/withdraw$', views.tutorwithdraw, name='tutorwithdraw'),
    url(r'^admin/triggersession$', views.triggersession, name='triggersession'),
    url(r'^(?P<myuser_id>[0-9]+)/$', views.index, name='index'),
    url(r'^(?P<myuser_id>[0-9]+)/searchTutors/(?P<tutor_id>[0-9]+)/$', views.tutorpage, name='tutorpage'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/$', views.myaccount, name='myaccount'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mybooking/$', views.mybooking, name='mybooking'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mybooking/evaluate/(?P<tutorial_sessions_id>[0-9]+)/$', views.evaluate,
        name='evaluate'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/myprofile/$', views.myprofile, name='myprofile'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mywallet/$', views.mywallet, name='mywallet'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mytransaction/$', views.mytransaction, name='mytransaction'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mywallet/deposit/$', views.deposit, name='deposit'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mywallet/withdraw/$', views.withdraw, name='withdraw'),
    url(r'^(?P<myuser_id>[0-9]+)/message/$', views.message, name='message'),
    url(r'^(?P<myuser_id>[0-9]+)/timeslot/(?P<tutor_id>[0-9]+)/$', views.selectbooking, name='timeslot'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/mybooking/cancelled/(?P<tutorial_sessions_id>[0-9]+)/$', views.cancelbooking, name='cancelbooking'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register_page, name='register'),
    url(r'^(?P<myuser_id>[0-9]+)/searchTutorName/$', views.search_tutor_name, name='search_tutor_name'),
    url(r'^(?P<myuser_id>[0-9]+)/searchTutorTag/$', views.search_tutor_tag, name='search_tutor_tag'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/tutorTimeslot/(?P<tutor_id>[0-9]+)/$', views.tutorTimeslot, name='tutorTimeslot'),
    url(r'^(?P<myuser_id>[0-9]+)/myAccount/tutorTimeslotSelect/(?P<tutor_id>[0-9]+)/$', views.tutorTimeslotSelecting, name='tutorTimeslotSelecting'),

    #url(r'^registerSuccess/$', views.register_page, name='registerSuccess'),
    #test
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyTutor/Tutorial/views.py
from ast import literal_eval
from django.contrib import auth
from django.template import RequestContext
from django.shortcuts import redirect
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404, render, render_to_response
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date, datetime, time, timedelta
from Tutorial.forms import *
import time
from Tutorial.models import *
from django.template import RequestContext
import logging
import re
# Get an instance of a logger
logger = logging.getLogger(__name__)
from django.contrib.auth import views as auth_views

from django.conf import settings
import smtplib
from django.core.mail import send_mail
import operator
import logging
from decimal import Decimal

# Get an instance of a logger
logger = logging.getLogger(__name__)

from .forms import SearchForm


COMMISION = 1.05
# Create your views here.
class HomePageView(TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'index.html', context=None)

class SearchedTutor(object):
    tutor = ""
    hourly_rate = 0
    tags = []
    teachCourse = []
    def __init__(self, tutor, hourly_rate, tags, teachCourse):
        self.tutor = tutor
        self.hourly_rate = hourly_rate
        self.tags = tags
        self.teachCourse = teachCourse

#####homepage###
def home(request):
    if not request.user.is_authenticated() or request.user.is_anonymous():
        #every function will have this, to make sure guest cannot visit personal account by manipulating url
        return render(request, 'home.html')
    if not MyUser.objects.filter(user=request.user):
        return HttpResponseRedirect('/Tutorial/admin/')
    myuser = MyUser.objects.get(user=request.user) #fixme if an admin want to go to Tutorial/, he is not a myuser
    return HttpResponseRedirect('/Tutorial/' + str(myuser.id)) #searchTutors/'+str(request.user.id)
####login####
def login(request):
    if request.user.is_authenticated(): #visitor or client
        if not MyUser.objects.filter(user=request.user):
            return HttpResponseRedirect('/Tutorial/admin/') # Assume all tutors share a same page, so noneed for user.id+ str(user.id))
        myuser = MyUser.objects.get(user=request.user)
        return HttpResponseRedirect('/Tutorial/' + str(myuser.id)) #searchTutors/'+str(request.user.id)

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    user = auth.authenticate(username=username, password=password) #if sucess, should get not none

    if user is not None and user.is_active:
        auth.login(request, user)
        if not MyUser.objects.filter(user=request.user):
            return HttpResponseRedirect('/Tutorial/admin/') # Assume all tutors share a same page, so noneed for user.id+ str(user.id))
        myuser = MyUser.objects.get(user=request.user)
        return HttpResponseRedirect('/Tutorial/' + str(myuser.id))
    else:
        return render(request, 'registration/login.html')

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/Tutorial/')
"""def password_reset(request):
    return render( 'registration/password_reset_form.html')

def password_reset_done(request):
    return render('/registration/password_reset_done.html')

def password_reset_confirm(requst):
    return HttpResponseRedirect('/Tutorial/')

def password_reset_complete(request):
    return HttpResponseRedirect('/Tutorial/')"""


####search tutor####
def index(request, myuser_id):
    show_tags = []
    if not request.user.is_authenticated() or request.user.is_anonymous(): #visitor or client
        return render(request, 'home.html')
    if not MyUser.objects.filter(user=request.user):
        return HttpResponseRedirect('/Tutorial/admin/')
    myuser = MyUser.objects.get(user=request.user)  # myuser = get_object_or_404(MyUser, pk=myuser_id)
    #fixme I do this to make sure you are the person you should be, you cannot be someone else
    #fixme  but I haven't tried how to also relink the url i.e. if id = 2 enter 3/..., the content can be
    #fixme 2's now ,but the url shows 3 still

    all_tutors = Tutor.objects.filter(showProfile=True)
    for tut in all_tutors:
        show_tags.append(tut.tag_set.all())
    private_tutors = PrivateTutor.objects.all()
    courses= Course.objects.all()
    zipped = zip(all_tutors, show_tags)
    params = {"user": myuser, "latest_Tutor_list": all_tutors, "tutors": zipped, 'courses': courses}
    return render(request, 'searchtutors/index.html', params)

def adminpage(request):
    return render(request, 'admin.html')

def triggersession(request):
    time = request.POST['time']
    timeformat = '%Y%m%d%H%M'
    try:
        bookingtime = datetime.strptime(time, timeformat)
    except Exception as e:
        return render(request, 'admin.html', {"msg": "Please enter format: YYYYmmddHHMM"})
    logger.error("trigger time wanted at" + time)
    if bookingtime.minute != 0 and bookingtime.minute != 30:
        return render(request, 'admin.html', {"msg": "Minutes is not 00 or 30, so no effect"})
    locksession(time)

    endsession(time)
    return render(request, 'admin.html', {"msg": "Setting success"})

def locksession(mytime):
    timeformat = '%Y%m%d%H%M'
    reftime = datetime.strptime(mytime, timeformat)
    if reftime.weekday() == 6 and reftime.hour == 0 and reftime.minute == 0:
        ## update the week of timeslot, if it is Sunday 00:00, then the timeslot should switch to a new week
        for tutor in Tutor.objects.all():
            if tutor.hourly_rate == 0:
                trigger = 2
            else: trigger = 1 #this is to distinguish between the two kinds
            slotlist = tutor.timeslot
            mid = 168 * trigger
            first_half = slotlist[mid: ] #the first half should be the second half of previous slot, next week has become the current week
            second_half = '1' * mid
            tutor.timeslot = first_half + second_half
            tutor.save()

    for slot in TutorialSession.objects.all(): #for this tutor's session, for student is this student , for loop
        ## begin tutorial
        if slot.starttime == mytime:
            if slot.status == 0 or slot.status == 1: #meaning that this session is upcoming but not canceled
                slot.status = 5 #set to in progress
                slot.save()
        else:
        ## lock cancel
            nowbooking = datetime.strptime(slot.starttime,timeformat)  # this is the yy mm dd format for what student wants to book
            bookingtime = time.mktime(nowbooking.timetuple())  # transfrom nowbooking into time format, should expect this to be later
            bookingreftime = time.mktime(reftime.timetuple()) # transform the reftime into time format
            logger.error("This is slot's time " + str(bookingtime) + " and this is now time " + str(bookingreftime) + " and this is the time delta " + str((bookingtime - bookingreftime) / 3600))
            if (slot.status == 0 and (bookingtime - bookingreftime) / 3600 <= 24): #if it is upcoming, make it cannot be canceled
                slot.status = 1
                slot.save()

    ## close booking

    now = reftime #only test for within one week!!
    #now = datetime.now()
    showingtime = time.mktime(datetime(now.year, now.month, now.day, 0, 0).timetuple())
    bookingtime = time.mktime(now.timetuple()) #transfrom nowbooking into time format
    #later on with beginAllSessions, we update the available string for every tutor each week at the end
    #day difference is because the 14-day long string starts from this Sunday, the first day of the week
    hour_diff = (bookingtime - showingtime) / 3600
    weekday = (1 + now.weekday()) % 7  # Monday is 0 ... Sunday is 6, but Sunday is the first day of the week, transform to 0
    if reftime.minute == 0:
        for tutor in Tutor.objects.all():

            if tutor.hourly_rate == 0:
                diff = 2
            else: diff = 1

            # modify timeslot string
            timeslot = list(tutor.timeslot)
            logger.error("This is the index" + tutor.myuser.user.username + " " + str(len(timeslot)) + " " + str(weekday * 24 * diff + int (hour_diff * diff) + 24 * diff) + " and " + str(weekday * 48 + hour_diff * 2 + 48))
            logger.error("Finally " + str(weekday * 24 * diff + int (hour_diff * diff) + 24 * diff))
            timeslot[weekday * 24 * diff + int (hour_diff * diff) + 24 * diff] = '3' #meaning this session has passed the state to be modified

            #weekday * 24 * diff is how many 24 hours has passed
            #int (hour_diff * diff) means starting from today to 'now', hong long has passed
            #24 * diff means 24 hours passed
            #this function works when we are in the first week in timeslot string, because it should be updated every Saturday night, why now
            #I pretend today is next Wednesday and it fails is because it change the time of the current week, but in practical the next week
            #should be the reall current week, so it works well
            tutor.timeslot = "".join(timeslot)
            tutor.save()
    else: #then only contracted tutor needed in this case, but currently now working because no interface for half an hour yet
        half_hour_diff = int((bookingtime - showingtime) / 1800)
        weekday = (1 + now.weekday()) % 7  # Monday is 0 ... Sunday is 6, but Sunday is the first day of the week, transform to 0
        for tutor in Tutor.objects.filter(hourly_rate=0):

            # modify timeslot string
            timeslot = list(tutor.timeslot) 
            timeslot[weekday * 48 + half_hour_diff + 48] = '3' #meaning I book the session, 0 only means tutor doesn't want this session to be booked
            logger.error(

MyTutor/Tutorial/templates/searchtutors/index.html
{% extends "Menu.html" %}
{% block title %}: search tutor{% endblock %}
{% block content %}
<section class="bg-parallax parallax-window" onload="getValue();" xmlns:Tutorial="http://www.w3.org/1999/xhtml">
        <div class="overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
              <div class="parallax-text">
                <h2 class="parallax_t __white">Search For Tutor</h2>
                <p>Please verify the searching tags</p>
                  <select class="form-control __plannerSelect" onchange="modeChange(this)" name="selectMode">
                      <option value="1" selected='selected'id="byTags">Search by tags</option>
                      <option value="2" id="byName">Search by tutor's name</option>
                  </select>
              </div>
            </div>
            <!-- planner-->
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 planner">
              <div class="planner-block" id="planner" value="testing">
                <form class="form-planner form-horizontal" id="SearchByTag" action="{% url 'Tutorial:search_tutor_tag' user.id %}" method="get" >
                    {% csrf_token %}
                  <div class="row" >
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                      <div class="form-group">
                        <label>University</label>
                        <select class="form-control __plannerSelect" name="university">
                              <option value="HKU">HKU</option>
                        </select>
                      </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                      <div class="form-group">
                        <label>University course</label>
                        <select class="form-control __plannerSelect" name="course">
                              <option  value=""></option>
                                {% for course in courses %}
                                <script>
                                    var c = "{{course}}";
                                    document.write("<option  value=\""+c +"\">{{course}}</option>")
                              </script>
                            {% endfor %}
                        </select>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                      <div class="form-group">
                          <label id="tags">Subject Tags</label>
                          <input type="text" class="form-control" placeholder="Enter the key words to seach tags" id="subjectTags" name="tags" action="">
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                      <div class="form-group">
                          <label>Tutor Type</label>
                          <div class="theme-select">
                            <select class="form-control __plannerSelect" name="type" >
                                <option value=""></option>
                              <option  value="PrivateTutor">Private Tutor</option>
                              <option  value="ContractedTutor">Contracted Tutor</option>
                            </select>
                          </div>
                        </div>
                      </div>
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                      <div class="form-group">
                          <label>Showing Option </label>
                           <select class="form-control __plannerSelect" name="option">
                              <option  value="AllTutors">All tutors</option>
                              <option  value="TutorWithin7Days">Tutors with at least one available timeslot in the next 7 days.</option>
                            </select>
                        </div>
                      </div>
                  </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                          <div class="form-group">
                  <label>Order</label>
                               <select class="form-control __plannerSelect" name="order">
                                  <option  value="Random"></option>
                                  <option  value="Rate high to low">Rate high to low</option>
                                   <option  value="Rate low to high">Rate low to high</option>
                                   <option  value="High average">High average</option>
                                </select>
                            </div>
                          </div>

                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                            <input type="button"  class="btn btn-default" value="Show Price Range" id="priceRange">
                    </div>

                  <div class="row"  id="Price">
                    <div class="col-lg-6 col-md-12 col-sm-12">
                      <div class="form-group">
                          <!-- div id="slider-range"></div>
                          <div id="amount"><span id="amount1"></span><span id="amount2"></span></div>
                          <script>
                              var lowPrice = document.getElementById("amount1").value;
                              var highPrice = document.getElementById("amount2").value;
                              document.write("<input type=\"hidden\" name=\"lowPrice\" value=\""+lowPrice+"\">\n" +
                                  "                          <input type=\"hidden\" name=\"highPrice\" value=\""+highPrice+"\">");
                            </script -->
                            <label>Low Rate</label>
                            <input type="text" class="form-control"   name="lowPrice">-
                        </div>
                      </div>
                      <div class="col-lg-6 col-md-12 col-sm-12">
                      <div class="form-group">
                            <label>High Rate</label>
                            <input type="text" class="form-control"   name="highPrice">
                        </div>
                      </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                      <div class="planner-check-availability">
                        <input type="submit"  class="btn btn-default" value="Check availability">
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <!-- /planner-->
          </div>
        </div>
    </section>
    <!-- /parallax -->

    <!-- Best Tutor -->
    <section class="best-tutor">
      <div class="container">
        <div class="title-main">
          <h2 class="h2">Are you interested in them ?<span class="title-secondary">Look Our Best Tutors</span></h2>
        </div>

        <div class="best-tutor-carousel">
          <ul class="row best-tutor_ul">
              {%for Tutor,Tags in tutors%}
            <li class="col-lg-4 col-md-4 col-sm-6 col-xs-12 best-tutor_li">
              <div class="best-tutor_img">

                <a href="{% url 'Tutorial:tutorpage' user.id Tutor.id %}">
                    {% if Tutor.myuser.image %}
                        <img src="{{ Tutor.myuser.image.url }}" alt="">
                    {% else %}
                        <img src="/static/bootstrap/images/best-rooms/1.jpg" alt="">
                    {% endif %}
                </a>
                <div class="best-tutor_overlay">
                  <div class="overlay_icn"><a href="{% url 'Tutorial:tutorpage' user.id Tutor.id %}"></a></div>
                </div>
              </div>
              <div class="best-tutor-info">
                  <div class="best-tutor_t"><a href="{% url 'Tutorial:tutorpage' user.id Tutor.id %}">{{ Tutor.myuser.user.username }} ({{Tutor.university}})</a></div>
                  <div class="best-tutor_t"><a href="{% url 'Tutorial:tutorpage' user.id Tutor.id %}">{{Tutor.myuser.user.first_name}} {{Tutor.myuser.user.last_name}}</a></div>
                  <div class="best-tutor_t">Tags :
                      {% for Tag in Tags %}
                         <span>{{Tag}} , </span>
                      {% endfor %}
                  </div>

                <div class="best-tutor_rate">
                  <span>${{Tutor.hourly_rate}}</span>
                </div>
                   <script>
                      if ("{{Tutor.reviewed_times}}" >= 3){
                        document.write("<div class=\"best-tutor_t\">Average review score: <span class=\"spanType\">{{Tutor.average}}</span></div>");
                      }else{
                        document.write("<div class=\"best-tutor_t\">Average review score: <span class=\"spanType\">N/A</span></div>");
                      }
                  </script>
                  <div class="best-tutor_t"><a href="{% url 'Tutorial:tutorpage' user.id Tutor.id %}"><div class="btn btn-default" >Profile</div></a></div>
              </div>
            </li>
              {% endfor %}
          </ul>
        </div>
      </div>
    </section>

    <!-- /choose best tutors -->

{% endblock %}

{% block script %}

    var originalHTML;
     $(window).on('load', function () {
      originalHTML = document.getElementById("planner").innerHTML;
 });

    function modeChange(sobj){
    var idx = sobj.selectedIndex;
     if (idx == 1){
        var str = "<form class='form-planner form-horizontal' id='SearchByName' action='{% url 'Tutorial:search_tutor_name' user.id %}' method='get'>{% csrf_token %}<div class='row' ><div class='col-lg-6 col-md-6 col-sm-12 col-xs-12 '><div class='form-group'><label>Given Name</label> <input type='text' class='form-control' placeholder='Given name' name='givenName'></div></div><div class='col-lg-6 col-md-6 col-sm-12 col-xs-12'><div class='form-group'><label>Family Name</label><input class='form-control' id='FamilyName' type='text' placeholder='Family name' name='familyName'></div></div></div><div class='row'><div class='col-lg-12 col-md-12 col-sm-12'><div class='planner-check-availability'><input type='submit' class='btn btn-default'>Check availability</input></div></div></div></form>";        document.getElementById("planner").innerHTML =  str;
    }else{
        document.getElementById("planner").innerHTML =  originalHTML;
    }

    }


    $(document).ready(function(){

         var tags = new Array(10);
         i = 0;
         var strTags="";
        var deleteTags = "";

        $("#subjectTags").keypress(function (e) {
            var repeat = false;
            if (e.which == 13) {
                e.preventDefault();
                tags[i] = $("#subjectTags").val();
                if (tags[i] == ""){
                    alert("Tag cannot be empty!");
                    repeat = true;
                }
                var j = 0;
                for (j = 0;j < i;j++){
                    if(tags[j] == tags[i]){
                        alert("Tag " +tags[i]+" already exists!");
                        repeat = true;
                         $("#subjectTags").val("");
                        break;
                    }
                }
                if (repeat == false){
                    strTags = "<span style='background-color: lightgrey; color : black; margin : 2px; margin-left: 0; padding: 2px; ' id='"+tags[i]+"'><span style='background-color: lightgrey; color : darkred; padding : 2px; border:1px;'  id='deleteTags' target = '"+i+"'>X</span>";
                     strTags += ""+tags[i]+"</span>";
                    $("#tags").append(strTags);
                     $("#subjectTags").val("");
                     $("#subjectTags").html( "<input type='text' class='form-control' placeholder='Enter the key words to seach tags' id='subjectTags'name='tags' value='"+tags+"' >");
                    i++;
                 }

            }



        });
        $("#priceRange").click( function(){

            if (document.getElementById("Price").style.display != 'none'){
                document.getElementById("Price").style.display = 'none';
                document.getElementById("priceRange").value = 'Hide Price Range';
             }else{
                document.getElementById("Price").style.display = 'inline';
                document.getElementById("priceRange").value = 'Show Price Range';
    }




    });



    $(document).on('click', '#deleteTags', function(){

        var pare = $(this).parent();
        var tagContent = pare.attr('id');
        deleteTags += tagContent + ",";
        $("#subjectTags").html( "<input type='text' class='form-control' placeholder='Press enter to add tags.' id='subjectTags'name='tags' value='"+tags+"'><input type=\"hidden\" name='deleteTags' value='"+deleteTags+"'>");
        $(this).parent().remove();
    });
    });



{% endblock %}